---
- name: install collectd zookeeper plugin
  sudo: yes
  copy:
    src: zookeeper.py
    dest: /usr/share/collectd
    mode: u=r
  tags:
    - zookeeper
    - collectd

- name: configure collectd zookeeper plugin
  sudo: yes
  copy:
    src: zookeeper.conf
    dest: /etc/collectd.d
  notify:
    - restart collectd
  tags:
    - zookeeper
    - collectd
