---
- name: install collectd
  sudo: yes
  yum:
    name: collectd
    state: present
  tags:
    - collectd

- name: configure collectd
  sudo: yes
  template:
    src: collectd.conf.j2
    dest: /etc/collectd.conf
  notify:
    - restart collectd
  tags:
    - collectd
