---
- name: install collectd docker plugin dependencies
  sudo: yes
  pip:
    name: "{{ item }}"
    state: present
  with_items:
    - py-dateutil
    - docker-py>=1.0.0
  tags:
    - docker
    - collectd

- name: install collectd docker plugin
  sudo: yes
  copy:
    src: "{{ item }}"
    dest: "/usr/share/collectd/{{ item }}"
    mode: u=r
  with_items:
    - docker.py
    - docker.db

- name: configure collectd docker plugin
  sudo: yes
  copy:
    src: docker.conf
    dest: /etc/collectd.d/docker.conf
  notify:
    - restart collectd
  tags:
    - docker
    - collectd
